RandevuTakip.WebApp/Controllers/AppointmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using RandevuTakip.DAL.Abstract;
using RandevuTakip.Entities;
using RandevuTakip.Entities.Identity;
using RandevuTakip.Entities.Identity.Security;

namespace RandevuTakip.WebApp.Controllers
{
    [Authorize]
    public class AppointmentController : Controller
    {
        private readonly IAppointmentRepository appointmentRepo;
        private readonly IDoctorRepository doctorRepo;
        private readonly IPatientRepository patientRepo;
        private readonly IDepartmentRepository departmentRepo;
        private readonly UserManager<ApplicationUser> userManager;

        public AppointmentController(IAppointmentRepository _appointmentRepo,
                                     IDoctorRepository _doctorRepo, IPatientRepository _patientRepo, IDepartmentRepository _departmentRepo, UserManager<ApplicationUser> _userManager)
        {
            appointmentRepo = _appointmentRepo;
            doctorRepo = _doctorRepo;
            patientRepo = _patientRepo;
            departmentRepo = _departmentRepo;
            userManager = _userManager;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Reserved()
        {
            List<Appointment> reserveds = new List<Appointment>();

            var user = await userManager.GetUserAsync(User);          
            var role = await userManager.GetRolesAsync(user);

            if (role[0].Equals(Constants.Patient))
            {
                reserveds = appointmentRepo.GetReservedAppointmentsByPatientId(Convert.ToInt32(HttpContext.Session.GetString("UserId")));
                return View(reserveds);
            }
            else
            {
                reserveds = appointmentRepo.GetAppointmentsByDoctorId(Convert.ToInt32(HttpContext.Session.GetString("UserId")));
                return View("Appointments", reserveds);         
            }

        }

        [Authorize(Roles = Constants.Patient)]
        public IActionResult New()
        {
            return View();
        }

        [HttpPost]
        public bool MakeAppointment(int patientId ,int doctorId, int departmentId ,string date)
        {
            Appointment appointment = new Appointment();
            appointment.Doctor = doctorRepo.FindById(doctorId);
            appointment.Patient = patientRepo.FindById(patientId);
            appointment.Department = departmentRepo.FindById(departmentId);
            appointment.Timestamp = Convert.ToDateTime(date);

            try
            {
                appointmentRepo.Add(appointment);
                return true;
            }
            catch (Exception)
            {
                return false;
            }

        }
    }
}

RandevuTakip.WebApp/Views/Shared/_HeaderPartial.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
<header>
    <div class="container">
        <div class="row">
            <div class="logo">
                <a href="#"><img width="80px;" src="~/img/logo2.png" alt="logo"></a>
            </div>

            <div class="tools-top">
                <div class="avatar-profile">
                    <div class="user-edit">
                        <h4>@UserManager.GetUserName(User),</h4>
                        <a href="my-account.html">Profilim</a>
                    </div>
                    <div class="avatar-image">
                        <img src="img/avatar-profile.jpg" alt="avatar profile" class="img-responsive">
                    </div>
                </div>
                <ul class="tools-help">
                    @*
                        <li><a href="help.html" title="Help" data-toggle="tooltip" data-placement="bottom"><i class="fa fa-question-circle"></i></a></li>*@
                    <li>
                        <form method="post" action="~/Identity/Account/Logout">
                            <button type="submit" data-toggle="tooltip" data-placement="bottom"><i class="fa fa-sign-out"></i>Çıkış</button>
                        </form>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</header>

RandevuTakip.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<!-- Mirrored from html.iwthemes.com/mas/appointments-reserved-empty.html by HTTrack Website Copier/3.x [XR&CO'2014], Mon, 05 Nov 2018 14:20:08 GMT -->
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, minimum-scale=1,  maximum-scale=1">
    <meta name="Description" content="" />
    <meta name="author" content="" />
    <title>Randevu Takip App</title>
    <link href="~/css/bootstrap.min.css" rel="stylesheet" media="screen">
    <link href="/css/styles.css" rel="stylesheet" media="screen">
    <link href="~/lib/calendar/fullcalendar.min.css" rel="stylesheet" media="screen">
    <link href="/lib/select2/select2.min.css" rel="stylesheet" media="screen">
    <link href="~/lib/sweetalert/sweetalert2.min.css" rel="stylesheet" media="screen">
    <link rel="shortcut icon" type="image/ico" href="img/favicon.ico" />

    <script src="/js/jquery.js"></script>
    <script src="/js/jquery-ui.min.js"></script>
    <script src="/js/bootstrap.min.js"></script>
    <script src="/js/bootstrap-sprockets.js"></script>
    <script src="/js/main.js"></script>
    <script src="/lib/select2/select2.full.min.js"></script>
    <script src="~/lib/calendar/moment.min.js"></script>
    <script src="~/lib/calendar/fullcalendar.min.js"></script>
    <script src="~/lib/calendar/locale-all.js"></script>
    <script src="~/lib/calendar/tr.js"></script>
    <script src="~/lib/sweetalert/sweetalert2.min.js"></script>


</head>
<body>
    <div id="layout">
      <partial name="_HeaderPartial" />
        <partial name="_NavPartial" />
    </div>
    <section class="container">
        <div class="main-container">
            @RenderBody()
            </div>
        </section>
</body>



</html>

RandevuTakip.WebApp/Views/Shared/_NavPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using RandevuTakip.Entities.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<nav>
    <div class="container">
        <h4 class="navbar-brand">menu</h4>
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <i class="fa fa-bars" aria-hidden="true"></i>
            </button>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li class="active"> <i class="fa fa-list-alt"></i> <a asp-controller="Appointment" asp-action="Reserved"> Rezervasyonlarım</a> </li>
                @{
                    var user = await UserManager.GetUserAsync(User);
                    var role = await UserManager.GetRolesAsync(user);
                }
               @if (role[0].ToString().Equals("Patient"))
               {
               <li> <i class="fa fa-address-book-o"></i> <a asp-controller="Appointment" asp-action="New"> Yeni rezervasyon</a> </li>
               }
            </ul>
        </div>
    </div>
</nav>